name: pixel_tile_dm
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - matplotlib
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - pip